- hosts: localhost
  vars:
    curr_user: "{{ lookup('env', 'USER') }}"
    personal: "{{ lookup('env', 'HOME') }}/projects/personal"
  pre_tasks:
  - name: Update Apt
    become: true
    apt:
      force_apt_get: true
      update_cache: true
      state: present
    tags:
      - install
      - core
  tasks:
    - include: tasks/core-setup.yml
    - include: tasks/zsh-setup.yml
    - include: tasks/nvim-setup.yml
    - include: tasks/productivity-tools.yml
    - include: tasks/lsp.yml
