- name: Install System Packages 1 (base-devel, cmake, pkgconf, pthread)
  become: true
  pacman:
    name:
      - base-devel    
      - cmake
      - pkgconf       
    state: present
  tags:
    - install
    - neovim
    - core

- name: Install System Packages 2 (lua, unzip, libtool, gettext)
  become: true
  pacman:
    name:
      - lua51
      - unzip
      - libtool
      - gettext
  tags:
    - install
    - neovim
    - core

- name: Install System Packages 3 (the rest)
  become: true
  pacman:
    name:
      - man
      - vi
      - picom         
      - curl
      - htop
      - go            
      - lsof
      - i3-wm         
      - ccache
      - ninja
      - python-pip    
      - dconf-editor
      - moreutils
      - clang
      - less
      - npm
      - lua-language-server
  tags:
    - install
    - core

